apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: njthwb40k-python 
  janus-idp.io/tekton: njthwb40k-python
  backstage.io/kubernetes-id: njthwb40k-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: njthwb40k-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml