apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: njthwb40k-python
  janus-idp.io/tekton: njthwb40k-python
  backstage.io/kubernetes-id: njthwb40k-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: njthwb40k-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
